alter table if exists refresh_token drop constraint if exists fk_user_id;
alter table if exists subcategory drop constraint if exists fk_category_id;
alter table if exists product drop constraint if exists fk_subcategory_id;
alter table if exists user_product drop constraint if exists fk_product_id;
alter table if exists user_role drop constraint if exists fk_user_id;
alter table if exists user_product drop constraint if exists fk_user_id;
alter table if exists subcategory drop constraint if exists fk_subcategory_id;
alter table if exists user_feedback drop constraint if exists fk_user_id;
alter table if exists user_feedback drop constraint if exists fk_product_id;
alter table if exists photo drop constraint if exists fk_user_feedback_id;
alter table if exists product_property drop constraint if exists fk_product_id;
alter table if exists product_property drop constraint if exists fk_property_id;

drop table if exists "user" cascade;
drop table if exists user_role cascade;
drop table if exists category cascade;
drop table if exists refresh_token cascade;
drop table if exists subcategory cascade;
drop table if exists product cascade;
drop table if exists user_product cascade;
drop table if exists product_property cascade;
drop table if exists property cascade;
drop table if exists photo cascade;
drop table if exists user_feedback cascade;

create table "user"
(
    user_id bigint generated by default as identity,
    firstname varchar(255) not null,
    lastname varchar(255) not null,
    email varchar(255) not null,
    password varchar(255) not null,
    primary key (user_id)
);

create table user_role
(
    user_id bigint not null,
    role varchar(255) not null
);


create table product
(
    product_id bigint generated by default as identity,
    product_property_id bigint not null,
    title varchar(255) not null,
    description varchar(500) not null,
    amount bigint not null,
    picture_url varchar(500) not null,
    price bigint not null,
    discount_price bigint,
    discount boolean not null,
    subcategory_id bigint not null,
    primary key (product_id)
);

create table user_product
(
    user_product_id bigint generated by default as identity,
    user_id bigint not null,
    product_id bigint not null,
    amount bigint not null,
    primary key (user_product_id)
);

create table user_feedback
(
    user_feedback_id bigint generated by default as identity,
    user_id bigint not null,
    product_id bigint not null,
    feedback bigint not null,
    comment varchar(500),
    primary key (user_feedback_id)
);

create table photo
(
    photo_id bigint generated by default as identity,
    picture_url varchar(500),
    user_feedback_id bigint not null,
    primary key (photo_id)
);

create table property
(
    property_id bigint generated by default as identity,
    product_property_id bigint not null,
    name varchar(255) not null,
    value varchar(255) not null,
    primary key (property_id)
);

create table product_property
(
    product_property_id bigint generated by default as identity,
    primary key (product_property_id)
);

create table subcategory
(
    subcategory_id bigint generated by default as identity,
    parent_id bigint default null,
    category_id bigint not null,
    title varchar(255) not null,
    primary key (subcategory_id)
);

create table category
(
    category_id bigint generated by default as identity,
    title varchar(255) not null,
    primary key (category_id)
);

create table refresh_token
(
    token_id bigint generated by default as identity,
    token varchar(255) not null,
    user_id bigint not null,
    primary key (token_id)
);

alter table if exists user_product add constraint fk_product_id foreign key (product_id) references product;
alter table if exists user_product add constraint fk_user_id foreign key (user_id) references "user";
alter table if exists user_role add constraint fk_user_id foreign key (user_id) references "user";
alter table if exists subcategory add constraint fk_category_id foreign key (category_id) references category;
alter table if exists product add constraint fk_subcategory_id foreign key (subcategory_id) references subcategory;
alter table if exists subcategory add constraint fk_subcategory_id foreign key (parent_id) references subcategory;
alter table if exists product add constraint fk_product_property_id foreign key (product_property_id) references product_property;
alter table if exists property add constraint fk_product_property_id foreign key (product_property_id) references product_property;
alter table if exists photo add constraint fk_user_feedback_id foreign key (user_feedback_id) references user_feedback;
alter table if exists user_feedback add constraint fk_user_id foreign key (user_id) references "user";
alter table if exists user_feedback add constraint fk_product_id foreign key (product_id) references product;
alter table refresh_token add constraint fk_user_id foreign key (user_id) references "user";
