logging:
  level:
    web: DEBUG

server:
  forward-headers-strategy: native
  port: 8080
  error:
    include-message: always

spring:
  config:
    import: optional:file:.env[.properties]
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  flyway:
    baseline-on-migrate: true
    locations: classpath:db.migration
    schemas: public
    enabled: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false

springfox:
  documentation:
    swagger:
      v2:
        use-model-v3: false

shop:
  jwt:
    secret:
      access: ${JWT_ACCESS_SECRET}
      refresh: ${JWT_REFRESH_SECRET}
    expires:
      access-sec: 604800
      refresh-days: 30
